### ISSUE TITLE
License file missing in the repository

### ISSUE THREAD

**Issue by pratham-m** [openshift/images#56]
Hi,

I am working at IBM as a contributor to the development of the overall open source ecosystem for Power 8 LE systems.
To contribute to any opensource project, we need to get code contribution approvals within IBM, for which we need information on "**License**" used by the respective opensource project (GitHub repository).

I see that other repositories under https://github.com/openshift use Apache2.0 license, however there isn't any license file under https://github.com/openshift/images repository.
Could you kindly provide me information on which license this repository is supposed to use. It would be good if you can add the license file to the repository.

I am currently using the https://github.com/openshift/images/blob/master/base/Dockerfile.rhel as a base image to build other openshift images, and may have some code contributions to openshift/images repository, going further.

**Comment by pratham-m** [comment]
Hi, can anyone help me with this?

**Comment by gerrith3** [comment]
It looks like many of the files here claim to be copied from openshift/origin - which does have a LICENSE file of Apache 2.0.  @pratham-m can you confirm that all of the files here were copied from there?  If so, they would all be Apache 2.0 but they should still copy over the LICENSE file along with the rest.  That is kind of inappropriate to remember to preserve people's LICENSE files when effectively forking.  I think it may have been overlooked because this is viewed as "just images" or just image creation perhaps, but that's not a very good excuse for leaving that out.  :(

**Comment by smarterclayton** [comment]
All OpenShift projects are ASL2 unless otherwise stated.  I'll ask someone to make sure we have license files in place across all repos.

**Comment by pratham-m** [comment]
thanks @smarterclayton for the information.

**Comment by candita** [comment]
I trust this issue has been resolved. If not, please reopen.
/close
